### ISSUE TITLE
Add option to switch to next/previous day.

### ISSUE THREAD

**Issue by akoppela** [xendk/reaper#7]
It's in enchantment. It would be nice to switch to the next/prev day in a more easy way. The solution would be to add two additional functions. What do you think? If you like an idea I can file a PR for that.

**Comment by xendk** [comment]
Sure. The `n` and `p` keys are taken by `tabulated-list-mode`, so `f` (forward a day) and `b` (backwards a day) seems the obvious choice.

**Comment by akoppela** [comment]
Sounds good.

**Comment by akoppela** [comment]
BTW I'm using different key map. Because I'm using `evil-mode`. I think it's best to have a customization where people wants to use provided key-map or if they want to create their own key-map. What do you think?

**Comment by xendk** [comment]
I think it's great that Emacs allows for much configuration, but an end user aimed package should provide sensible defaults. Look at `dired` as an example, it binds everything the developer think you'd ever need.

**Comment by akoppela** [comment]
Yes defaults are great. What I mean is that if we can have an option to do not have default bindings for those who don't like them? By default only the bindings are available but it's possible to turn them off.

**Comment by xendk** [comment]
Is that really something you see often in Emacs packages? I know some kinda give up on finding a available key in the global keymap, but for packages with their own modes?

What keys are it exactly you don't like? I've only used `g` of the VI movement keys, but it's a pretty established convention in Emacs that g refreshes.

**Comment by akoppela** [comment]
I saw it a few times in my packages. (1) Some authors decide to do not provide key-map at all, letting consumers to decide. (2) Some authors decide to have default key-map bindings. (3) Some authors provide default key-map and an option to disable it, letting consumers to decide. Personally I like the third option. Because emacs is so great in customizations a lot of people like to roll their own emacs config.  Like it's a truly free software without imposing their views. What is your vision about that?

About the issue. Emacs has built in `calendar`. I think it would be nice to use it for dates. What do you think?

**Comment by xendk** [comment]
OK, this is getting deep, but...

> Because emacs is so great in customizations a lot of people like to roll their own emacs config. Like it's a truly free software without imposing their views. What is your vision about that?

Well, exactly because of the flexibility of Emacs it all boils down to how much to accommodate the special cases, which again is a matter of taste. One argument is that it's not much work to add a custom variable for disabling the keymap, another is that Emacs flexibility allows those who really want it to enforce it anyway and providing settings for the 10% case clutters the UI for everybody, which should be avoided.

The latter argument has been championed by Apple (and say what you want, they've had some success with that) and Gnome, while I gather that KDE is more of the first kind, demonstrating that it's a common theme.

Despite that I'm a Gnome user, I'm not going to object wildly if it shows up decently implemented in a PR. Though I'm still curious as to what bindings you're using?

> About the issue. Emacs has built in calendar. I think it would be nice to use it for dates. What do you think?

If you can make the date selector use the calendar that pops up on `M-x calendar`, that would be spiffy. I have no experience with calendar, so I don't know if it can be used like a widget like that.

**Comment by xendk** [comment]
Added `f` and `b` bindings. You can override `reaper-mode-map` if you don't like the defaults.
